apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-storage
  labels:
    app.kubernetes.io/name: backup-storage
    app.kubernetes.io/part-of: "254carbon"
provisioner: k3d.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  path: "/var/lib/rancher/k3s/storage/backups"
