apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-roles.yaml
  - cluster-role-bindings.yaml
  - service-accounts.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: "254carbon"
      app.kubernetes.io/managed-by: "kustomize"
