apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-kraft-server
  namespace: data-plane
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: "254carbon"
data:
  server.properties: |
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@127.0.0.1:9093
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka.data-plane.svc.cluster.local:9092
    inter.broker.listener.name=PLAINTEXT
    controller.listener.names=CONTROLLER
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data
    num.partitions=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    group.initial.rebalance.delay.ms=0
