apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-plane

resources:
  - kafka.yaml
  - jmx-exporter-config.yaml
  - log4j-console.yaml
  - kraft-server-config.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: "254carbon"
      tier: data
      domain: messaging
