apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-log4j-console
  namespace: data-plane
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: "254carbon"
data:
  log4j-console.properties: |
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n
