apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue-monitor
  labels:
    app.kubernetes.io/name: job-queue-monitor
    app.kubernetes.io/component: monitor
    app.kubernetes.io/part-of: carbon-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: job-queue-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: job-queue-monitor
        app.kubernetes.io/component: monitor
        app.kubernetes.io/part-of: carbon-platform
    spec:
      containers:
      - name: monitor
        image: 254carbon/job-queue-monitor:latest
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: job-queue-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: job-queue-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: job-queue-config
              key: REDIS_DB
        - name: JOB_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: job-queue-config
              key: JOB_QUEUE_NAME
        - name: MONITOR_INTERVAL_SECONDS
          value: "30"
        ports:
        - containerPort: 8001
          name: metrics
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: job-queue-monitor
  labels:
    app.kubernetes.io/name: job-queue-monitor
    app.kubernetes.io/component: monitor
    app.kubernetes.io/part-of: carbon-platform
spec:
  selector:
    app.kubernetes.io/name: job-queue-monitor
  ports:
  - port: 8001
    targetPort: 8001
    name: metrics
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job-queue-monitor
  labels:
    app.kubernetes.io/name: job-queue-monitor
    app.kubernetes.io/component: monitor
    app.kubernetes.io/part-of: carbon-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: job-queue-monitor
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
