apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: platform-core
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
data:
  password: cG9zdGdyZXMxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: ml
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==
  secret-key: bWluaW9hZG1pbjEyMw==
