apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: platform-core
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
data:
  password: cG9zdGdyZXMxMjM=
---
