# Local environment patches
# Adjustments for local k3d cluster

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: data-plane
spec:
  template:
    spec:
      containers:
      - name: clickhouse
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: data-plane
spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: data-plane
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: data-plane
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: kafka
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
      - name: kafka-jmx-exporter
        image: bitnami/jmx-exporter:latest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: data-plane
spec:
  template:
    spec:
      initContainers:
      - name: init-permissions-kafka
        image: busybox:1.36
        command:
        - sh
        - -c
        - chown -R 1000:1000 /var/lib/kafka/data
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: storage
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: minio
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        args:
        - server
        - /data
        - --console-address=:9001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: data-plane
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 999
        fsGroup: 999
      initContainers:
      - name: init-permissions-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - chown -R 999:999 /var/lib/postgresql/data
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: data-plane
spec:
  template:
    spec:
      containers:
      - name: clickhouse
        securityContext:
          readOnlyRootFilesystem: false
      securityContext:
        runAsNonRoot: false
        runAsUser: 101
        fsGroup: 101
      initContainers:
      - name: init-permissions-clickhouse
        image: busybox:1.36
        command:
        - sh
        - -c
        - chown -R 101:101 /var/lib/clickhouse
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: storage
spec:
  template:
    spec:
      initContainers:
      - name: init-permissions-minio
        image: busybox:1.36
        command:
        - sh
        - -c
        - chown -R 1000:1000 /data
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: minio-storage
          mountPath: /data
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-plane
  labels:
    name: data-plane
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-core
  labels:
    name: platform-core
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
