apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue-worker
spec:
  replicas: 5
  template:
    spec:
      nodeSelector:
        region: us-west
      tolerations:
      - key: region
        operator: Equal
        value: us-west
        effect: NoSchedule

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue-monitor
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        region: us-west

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-queue-config
data:
  MAX_WORKERS: "15"
  JOB_TIMEOUT: "7200"
