apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue-worker
spec:
  replicas: 8
  template:
    spec:
      nodeSelector:
        region: us-east
      tolerations:
      - key: region
        operator: Equal
        value: us-east
        effect: NoSchedule

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue-monitor
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        region: us-east

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-queue-config
data:
  MAX_WORKERS: "20"
  JOB_TIMEOUT: "7200"
