apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: "254carbon"
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 256
      batch:
        send_batch_size: 512
        timeout: 5s
    exporters:
      logging:
        loglevel: warn
      prometheus:
        endpoint: 0.0.0.0:9464
        namespace: otelcol
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
