apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  namespace: data-plane
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
data:
  password: Y2xpY2tob3VzZTEyMw== # clickhouse123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-storage
  namespace: data-plane
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: "254carbon"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: data-plane
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: "254carbon"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clickhouse
        app.kubernetes.io/part-of: "254carbon"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8123
        - name: native
          containerPort: 9000
        env:
        - name: CLICKHOUSE_DB
          value: "default"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: password
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8123
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: clickhouse-storage
        persistentVolumeClaim:
          claimName: clickhouse-storage
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: data-plane
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: "254carbon"
spec:
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  - name: native
    port: 9000
    targetPort: 9000
  type: ClusterIP
