apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - prometheus.yaml
  - grafana.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: "254carbon"
      tier: platform
      domain: observability
