apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  namespace: observability
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: transactional
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  namespaceSelector:
    matchNames:
      - data-plane
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: observability
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: cache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  namespaceSelector:
    matchNames:
      - data-plane
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: observability
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: messaging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  namespaceSelector:
    matchNames:
      - data-plane
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: observability
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: storage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  namespaceSelector:
    matchNames:
      - storage
  endpoints:
    - port: api
      interval: 30s
      scrapeTimeout: 10s
      path: /minio/v2/metrics/cluster
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  namespace: observability
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: access
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  namespaceSelector:
    matchNames:
      - platform-core
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse
  namespace: observability
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: analytics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
  namespaceSelector:
    matchNames:
      - data-plane
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: web
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
