apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: "254carbon"
  security.254carbon.com/component: gatekeeper

resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.13/deploy/gatekeeper.yaml
  - constraint-templates/deny-excess-privileges.yaml
  - constraint-templates/restrict-hostpath.yaml
  - constraints/deny-excess-privileges.yaml
  - constraints/restrict-hostpath.yaml
