apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-run
  namespace: ml
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-tracking
  namespace: ml
imagePullSecrets:
  - name: ghcr-pull

