image:
  registry: registry-1.docker.io
  repository: bitnamicharts/mlflow
  tag: ''
  digest: sha256:590fd5ec61f17efa7d8fa9968791cfd85809763c79a589b58c2519d9a303a94c
  pullPolicy: IfNotPresent
tracking:
  replicaCount: 1
  host: 0.0.0.0
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 24
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  livenessProbe:
    enabled: true
    initialDelaySeconds: 40
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 5
  persistence:
    enabled: false
  networkPolicy:
    enabled: false
  metrics:
    enabled: false
postgresql:
  enabled: false
externalDatabase:
  dialectDriver: postgresql
  host: postgresql.data-plane.svc.cluster.local
  port: 5432
  user: postgres
  database: 254carbon
  existingSecret: postgres-credentials
  existingSecretPasswordKey: password
minio:
  enabled: false
externalS3:
  host: minio.storage.svc.cluster.local
  port: 9000
  protocol: http
  bucket: mlflow-artifacts
  serveArtifacts: true
  useCredentialsInSecret: true
  existingSecret: minio-credentials
  existingSecretAccessKeyIDKey: access-key
  existingSecretKeySecretKey: secret-key
global:
  security:
    allowInsecureImages: true
