apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    app.kubernetes.io/name: backup
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: backup
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backup-quota
  namespace: backup
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: backup-limits
  namespace: backup
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
