apiVersion: v1
kind: Namespace
metadata:
  name: data-plane
  labels:
    app.kubernetes.io/name: data-plane
    app.kubernetes.io/part-of: "254carbon"
    tier: data
    domain: storage
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-plane-quota
  namespace: data-plane
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "20"
    pods: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: data-plane-limits
  namespace: data-plane
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    type: Container
