apiVersion: v1
kind: Namespace
metadata:
  name: ml
  labels:
    app.kubernetes.io/name: ml
    app.kubernetes.io/part-of: "254carbon"
    tier: platform
    domain: ml
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ml-quota
  namespace: ml
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    persistentvolumeclaims: "100"
    pods: "400"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ml-limits
  namespace: ml
spec:
  limits:
  - default:
      cpu: "4"
      memory: "4Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
