apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup
  namespace: backup
  labels:
    app.kubernetes.io/name: clickhouse-backup
    app.kubernetes.io/part-of: "254carbon"
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: clickhouse-backup
            app.kubernetes.io/part-of: "254carbon"
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: clickhouse-backup
            image: clickhouse/clickhouse-server:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting ClickHouse backup..."
              clickhouse-backup create manual-$(date +%Y%m%d-%H%M%S)
              echo "Backup completed"
            env:
            - name: CLICKHOUSE_HOST
              value: "clickhouse.data-plane.svc.cluster.local"
            - name: CLICKHOUSE_PORT
              value: "9000"
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: password
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
