apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-backup-credentials
  namespace: backup
  labels:
    app.kubernetes.io/name: clickhouse-backup
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
stringData:
  username: default
  password: clickhouse123
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-credentials
  namespace: backup
  labels:
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
stringData:
  username: postgres
  password: postgres123
  database: "254carbon"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-credentials
  namespace: backup
  labels:
    app.kubernetes.io/name: backup-minio
    app.kubernetes.io/part-of: "254carbon"
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin123
