apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: "254carbon"
  security.254carbon.com/component: trivy-operator

resources:
  - https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.29.0/deploy/static/trivy-operator.yaml

patchesStrategicMerge:
  - config-patch.yaml
