apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-standards
  namespace: kube-system
  labels:
    app.kubernetes.io/name: pod-security-standards
    app.kubernetes.io/part-of: "254carbon"
data:
  restricted.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: restricted-pod
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: restricted-container
        image: nginx:alpine
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
